spring:

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/app_db}
    username: ${DB_USERNAME:app_user}
    password: ${DB_PASSWORD:app_password}

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
